# docker-compose.yml – refactor  edition
services:
  # 1) Build image once
  ridges-base:
    build:
      context: .
      target: runtime
    image: ridges-base:latest
    profiles: ["builder"]

  # 2) Runtime services
  subtensor:
    image: ridges-base:latest
    container_name: subtensor
    working_dir: /subtensor
    command: ["bash", "-c",
      "BUILD_BINARY=0 ./scripts/localnet.sh False --ws-external --enable-pow-faucet"]
    environment:
      - RUN_IN_DOCKER=1
    ports:
      - "9945:9945"
    networks: [ridgesnet]
    volumes:
      - subtensor-data:/subtensor/data
      - bt-wallets:/root/.bittensor

  miner:
    image: ridges-base:latest
    container_name: miner
    depends_on: [subtensor]
    working_dir: /app
    command: >
      bash -c "uvicorn miner.main:app --host 0.0.0.0 --port 7999"
    ports:
      - "7999:7999"            # Miner's FastAPI service
    environment:
      - SUBTENSOR_ADDRESS=ws://subtensor:9945
      - WALLET_NAME=miner_ridges
      - HOTKEY_NAME=default_ridges
    # env_file:                  # secrets & config specific to miner
    #   - ./miner/.env
    networks: [ridgesnet]
    volumes:
      - bt-wallets:/root/.bittensor

  validator:
    image: ridges-base:latest
    container_name: validator
    depends_on: [subtensor]
    working_dir: /app
    command: >
      bash -c "uv run validator/main.py"
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=replace-me
      - WALLET_NAME=validator_ridges
      - HOTKEY_NAME=default_ridges
    # env_file:git 
    #   - ./validator/.env       # validator-specific secrets
    networks: [ridgesnet]
    volumes:
      - bt-wallets:/root/.bittensor

# Shared network & volumes
networks:
  ridgesnet:
    driver: bridge

volumes:
  subtensor-data:
  bt-wallets:
