//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *EvaluatorPool) DeepCopyInto(out *EvaluatorPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *EvaluatorPool) DeepCopy() *EvaluatorPool {
	if in == nil {
		return nil
	}
	out := new(EvaluatorPool)
	in.DeepCopyInto(out)
	return out
}

func (in *EvaluatorPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *EvaluatorPoolList) DeepCopyInto(out *EvaluatorPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EvaluatorPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *EvaluatorPoolList) DeepCopy() *EvaluatorPoolList {
	if in == nil {
		return nil
	}
	out := new(EvaluatorPoolList)
	in.DeepCopyInto(out)
	return out
}

func (in *EvaluatorPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *EvaluatorPoolSpec) DeepCopyInto(out *EvaluatorPoolSpec) {
	*out = *in
	out.Scaling = in.Scaling
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(EvaluatorPoolResources)
		(*in).DeepCopyInto(*out)
	}
}

func (in *EvaluatorPoolSpec) DeepCopy() *EvaluatorPoolSpec {
	if in == nil {
		return nil
	}
	out := new(EvaluatorPoolSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *EvaluatorPoolResources) DeepCopyInto(out *EvaluatorPoolResources) {
	*out = *in
	if in.Screener != nil {
		in, out := &in.Screener, &out.Screener
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Dind != nil {
		in, out := &in.Dind, &out.Dind
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

func (in *EvaluatorPoolResources) DeepCopy() *EvaluatorPoolResources {
	if in == nil {
		return nil
	}
	out := new(EvaluatorPoolResources)
	in.DeepCopyInto(out)
	return out
}

func (in *EvaluatorPoolScaling) DeepCopyInto(out *EvaluatorPoolScaling) {
	*out = *in
}

func (in *EvaluatorPoolScaling) DeepCopy() *EvaluatorPoolScaling {
	if in == nil {
		return nil
	}
	out := new(EvaluatorPoolScaling)
	in.DeepCopyInto(out)
	return out
}

func (in *EvaluatorPoolStatus) DeepCopyInto(out *EvaluatorPoolStatus) {
	*out = *in
	if in.LastScaleUpTime != nil {
		in, out := &in.LastScaleUpTime, &out.LastScaleUpTime
		*out = (*in).DeepCopy()
	}
	if in.LastScaleDownTime != nil {
		in, out := &in.LastScaleDownTime, &out.LastScaleDownTime
		*out = (*in).DeepCopy()
	}
	if in.LastPollTime != nil {
		in, out := &in.LastPollTime, &out.LastPollTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *EvaluatorPoolStatus) DeepCopy() *EvaluatorPoolStatus {
	if in == nil {
		return nil
	}
	out := new(EvaluatorPoolStatus)
	in.DeepCopyInto(out)
	return out
}
