"""Add Internal Flag model

Revision ID: e1bb1c104ea1
Revises: d8e2f4a6c1b0
Create Date: 2026-05-08 16:55:56.793355

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e1bb1c104ea1"
down_revision: Union[str, Sequence[str], None] = "d8e2f4a6c1b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "internal_flags",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "name",
            sa.Enum("VALIDATORS_PAUSED", "BLACKLISTED_VALIDATORS", name="internalflagname"),
            nullable=False,
            comment="The name of the flag, e.g. 'VALIDATORS_PAUSED'",
        ),
        sa.Column(
            "value",
            sa.Text(),
            nullable=False,
            comment="The value of the flag, stored as a string. Interpretation depends on the flag.",
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="A description of what the flag does"),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("NOW()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("internal_flags")
    # ### end Alembic commands ###
