"""block_extrinsic_index_to_refunds

Revision ID: c880b27e2afe
Revises: 234ed0606f2a
Create Date: 2026-05-07 11:03:36.448663

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c880b27e2afe"
down_revision: Union[str, Sequence[str], None] = "234ed0606f2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Add column with default value to backfill existing records, then remove default value to avoid unintended defaults for new records
    op.add_column(
        "failed_upload_refunds",
        sa.Column(
            "block_extrinsic_index",
            sa.Text(),
            nullable=False,
            comment="The block extrinsic index of the transaction associated with the agent upload that failed and caused the refund",
            server_default="",
        ),
    )
    op.alter_column(
        "failed_upload_refunds",
        "block_extrinsic_index",
        server_default=None,
    )
    # Add column with default value to backfill existing records, then remove default value to avoid unintended defaults for new records
    op.add_column(
        "failed_upload_refunds",
        sa.Column(
            "upload_block_extrinsic_index",
            sa.Text(),
            nullable=False,
            comment="The block extrinsic index of the transaction associated with the agent upload that failed and caused the refund",
            server_default="",
        ),
    )
    op.alter_column(
        "failed_upload_refunds",
        "upload_block_extrinsic_index",
        server_default=None,
    )
    op.alter_column(
        "failed_upload_refunds",
        "tx_hash",
        existing_type=sa.TEXT(),
        comment="The transaction hash of the refund transaction",
        existing_nullable=False,
    )
    op.alter_column(
        "failed_upload_refunds",
        "block_hash",
        existing_type=sa.TEXT(),
        comment="The block hash of the refund transaction",
        existing_nullable=False,
    )
    op.alter_column(
        "failed_upload_refunds",
        "amount",
        existing_type=sa.BIGINT(),
        comment="The amount to refund in RAO",
        existing_nullable=False,
    )
    op.alter_column(
        "failed_upload_refunds",
        "upload_tx_hash",
        existing_type=sa.TEXT(),
        comment="The transaction hash of the transaction associated with the agent upload that failed and caused the refund",
        existing_nullable=False,
    )
    op.alter_column(
        "failed_upload_refunds",
        "upload_block_hash",
        existing_type=sa.TEXT(),
        comment="The block hash of the transaction associated with the agent upload that failed and caused the refund",
        existing_nullable=False,
    )
    op.alter_column(
        "failed_upload_refunds",
        "upload_amount",
        existing_type=sa.BIGINT(),
        comment="The transfer amount in RAO of the transaction associated with the agent upload that failed and caused the refund",
        existing_nullable=False,
    )
    op.alter_column(
        "failed_upload_refunds",
        "coldkey",
        existing_type=sa.TEXT(),
        comment="The coldkey of the miner for which the upload failed and caused the refund",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "failed_upload_refunds",
        "coldkey",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="The coldkey of the miner for which the upload failed and caused the refund",
        existing_nullable=False,
    )
    op.alter_column(
        "failed_upload_refunds",
        "upload_amount",
        existing_type=sa.BIGINT(),
        comment=None,
        existing_comment="The transfer amount in RAO of the transaction associated with the agent upload that failed and caused the refund",
        existing_nullable=False,
    )
    op.alter_column(
        "failed_upload_refunds",
        "upload_block_hash",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="The block hash of the transaction associated with the agent upload that failed and caused the refund",
        existing_nullable=False,
    )
    op.alter_column(
        "failed_upload_refunds",
        "upload_tx_hash",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="The transaction hash of the transaction associated with the agent upload that failed and caused the refund",
        existing_nullable=False,
    )
    op.alter_column(
        "failed_upload_refunds",
        "amount",
        existing_type=sa.BIGINT(),
        comment=None,
        existing_comment="The amount to refund in RAO",
        existing_nullable=False,
    )
    op.alter_column(
        "failed_upload_refunds",
        "block_hash",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="The block hash of the refund transaction",
        existing_nullable=False,
    )
    op.alter_column(
        "failed_upload_refunds",
        "tx_hash",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="The transaction hash of the refund transaction",
        existing_nullable=False,
    )
    op.drop_column("failed_upload_refunds", "upload_block_extrinsic_index")
    op.drop_column("failed_upload_refunds", "block_extrinsic_index")
    # ### end Alembic commands ###
