"""payment agent ID optional

Revision ID: de54176da579
Revises: b8d3f6e2c9a5
Create Date: 2026-04-28 17:27:59.460081

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de54176da579"
down_revision: Union[str, Sequence[str], None] = "b8d3f6e2c9a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "evaluation_payments",
        "agent_id",
        existing_type=sa.UUID(),
        nullable=True,
        comment="Agent ID associated with this evaluation payment. The payment row is first created with no agent ID to claim an evaluation payment for a specific block hash + extrinsic index.",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "evaluation_payments",
        "agent_id",
        existing_type=sa.UUID(),
        nullable=False,
        comment=None,
        existing_comment="Agent ID associated with this evaluation payment. The payment row is first created with no agent ID to claim an evaluation payment for a specific block hash + extrinsic index.",
    )
    # ### end Alembic commands ###
