name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
    paths:
      - 'validator/sandbox/Dockerfile'
      - 'validator/sandbox/requirements.txt'
      - 'validator/sandbox/proxy/Dockerfile'
      - 'validator/sandbox/proxy/default.conf.template'
      - '.github/workflows/build-and-push-docker.yml'
      - 'validator/sandbox/agent_runner.py'

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - name: sandbox
            context: ./validator/sandbox
            dockerfile: ./validator/sandbox/Dockerfile
            image: ghcr.io/ridgesai/ridges/sandbox
          - name: proxy
            context: ./validator/sandbox/proxy
            dockerfile: ./validator/sandbox/proxy/Dockerfile
            image: ghcr.io/ridgesai/ridges/proxy

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Check for changed files
      id: changed-files
      run: |
        if [ "${{ matrix.name }}" == "sandbox" ]; then
          CHANGED=$(git diff --name-only HEAD^ HEAD | grep -E '^validator/sandbox/' | grep -v '^validator/sandbox/proxy/' | wc -l)
        else
          CHANGED=$(git diff --name-only HEAD^ HEAD | grep -E '^validator/sandbox/proxy/' | wc -l)
        fi
        echo "changed=$CHANGED" >> $GITHUB_OUTPUT
        echo "should_build=true" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for ${{ matrix.name }} image
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ matrix.image }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push ${{ matrix.name }} image
      uses: docker/build-push-action@v6
      with:
        context: ${{ matrix.context }}
        file: ${{ matrix.dockerfile }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: |
          type=gha,scope=${{ matrix.name }}
          type=registry,ref=${{ matrix.image }}:cache
        cache-to: |
          type=gha,mode=max,scope=${{ matrix.name }}
          type=registry,ref=${{ matrix.image }}:cache,mode=max
        provenance: false
        sbom: false 