name: Test Suite

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build and run tests with Docker Compose
      run: |
        cd tests
        docker-compose -f docker-compose.test.yml up -d
        
        # Wait for services to be ready
        echo "Waiting for PostgreSQL to be ready..."
        timeout 60s bash -c "until docker-compose -f docker-compose.test.yml exec -T postgres-test pg_isready -U test_user -d postgres; do sleep 1; done"
        
        # Build and run test container
        docker build -t ridges-test -f ../Dockerfile.test ..
        docker run --rm \
          --network tests_default \
          -e POSTGRES_TEST_URL=postgresql://test_user:test_password@postgres-test:5432/postgres \
          -e AWS_MASTER_USERNAME=test_user \
          -e AWS_MASTER_PASSWORD=test_password \
          -e AWS_RDS_PLATFORM_ENDPOINT=postgres-test \
          -e AWS_RDS_PLATFORM_DB_NAME=postgres \
          -e PGPORT=5432 \
          -v ${{ github.workspace }}:/app \
          ridges-test
        
        # Run linting in the same container
        docker run --rm \
          -v ${{ github.workspace }}:/app \
          ridges-test \
          bash -c "uv run ruff check tests/ --fix || true && uv run mypy tests/test_miner_agent_flow.py --ignore-missing-imports || true"
        
        # Cleanup
        docker-compose -f docker-compose.test.yml down
    
    - uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: false
